apiVersion: batch/v1
kind: CronJob
metadata:
  name: job-clear-session
spec:
  schedule: "0 0 * * MON"
  startingDeadlineSeconds: 200
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: clear-session
            image: django_app
            imagePullPolicy: Never
            envFrom:
            - secretRef:
                name: my-secret
            ports:
            - containerPort: 80
              protocol: TCP
            command:
            - /bin/sh
            - -c
            - date; echo Clear Session; python3 manage.py clearsessions
          restartPolicy: OnFailure
