apiVersion: batch/v1
kind: Job
metadata:
  name: job-make-migrate
spec:
  backoffLimit: 2
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: make-migrate
        image: django_app
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: my-secret
        ports:
        - containerPort: 80
          protocol: TCP
        command:
        - /bin/sh
        - -c
        - date; echo Clear Session; python3 manage.py migrate
      restartPolicy: OnFailure
